version: '3'

services:
  covid19-service:
    image: covid19-service
    command: server
    ports:
      - 8083:8080
    networks:
      - covid19-service
      - observability
    environment:
      ADDRESS: https://api.covid19api.com
      TRACER_AGENT_ADDRESS: jaeger-tracing:5775
#    depends_on:
#      - consul-server

networks:
  covid19-service:
    driver: bridge
  observability:
    external:
      name: observability_observability
